modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/HO-Artisan/BurstDoorOpen/issues"

[[mods]]
modId = "bdo"
version = "${mod_version}"
displayName = "Burst Door Open"
logoFile = "bdo.png"
authors = "Chemiofitor, RawDiamondMC"
description = '''Burst door open! Come on!'''

[[dependencies.bdo]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.bdo]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
